// <auto-generated />
namespace DocumentTracking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20_Jan_2019_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20_Jan_2019_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201902201217166_20_Jan_2019_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
